#!/bin/bash

# Works with
#
# - wasm-pack 0.12.1
# - wasm-opt version 114 (version_114-3-g5f6594c52)

set -e
set -x

OUT_DIR=site

mkdir -p $OUT_DIR

wasm-pack build crates/h10 --target web --release \
    --out-dir target/wasm-pack \
    --no-pack --no-typescript

cp crates/h10/target/wasm-pack/h10.js $OUT_DIR/h10.js
cp crates/h10/target/wasm-pack/h10_bg.wasm $OUT_DIR/h10_bg.wasm

# wasm-opt \
#     --closed-world -tnh -O4 --gufa -g \
#     --strip-debug --strip-dwarf --strip-producers --strip-target-features \
#     $OUT_DIR/h10_bg.wasm -o $OUT_DIR/h10_bg.wasm
# 
# wasm-opt \
#     --name-types -g \
#     -S $OUT_DIR/h10_bg.wasm -o $OUT_DIR/h10_bg.wat
